namespace MvcMusicStore.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateAlbum : DbMigration
    {
        public override void Up()
        {
            Sql(@"
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 4, N'For Those About To Rock We Salute You', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 4, N'Let There Be Rock', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 5, N'Balls to the Wall', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 5, N'Restless and Wild', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 5,N'Big Ones', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 9, N'Jagged Little Pill', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 10, N'Facelift', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 15, N'Audioslave', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 37, N'Chronicle, Vol. 1', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 37, N'Chronicle, Vol. 2', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 38, N'Into The Light', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Come Taste The Band', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Deep Purple In Rock', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Fireball', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Machine Head', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'MK III The Final Concerts [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Purpendicular', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Slaves And Masters', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'Stormbringer', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'The Battle Rages On', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 39, N'The Final Concerts (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 43, N'Un-Led-Ed', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 50, N'King For A Day Fool For A Lifetime', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 52, N'In Your Honor [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 52, N'In Your Honor [Disc 2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 52, N'The Colour And The Shape', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 53, N'Bongo Fury', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 59, N'Appetite for Destruction', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 59, N'Use Your Illusion I', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'A Matter of Life and Death', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Brave New World', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Fear Of The Dark', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Live At Donington 1992 (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Live At Donington 1992 (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Rock In Rio [CD2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'The Number of The Beast', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'The X Factor', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 61, N'Virtual XI', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 63, N'Emergency On Planet Earth', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 64, N'Are You Experienced?', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 65, N'Surfing with the Alien (Remastered)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 70, N'Greatest Kiss', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 70, N'Unplugged [Live]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'BBC Sessions [Disc 1] [Live]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'BBC Sessions [Disc 2] [Live]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Coda', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Houses Of The Holy', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'In Through The Out Door', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'IV', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Led Zeppelin I', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Led Zeppelin II', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Led Zeppelin III', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Physical Graffiti [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Physical Graffiti [Disc 2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'Presence', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'The Song Remains The Same (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 71, N'The Song Remains The Same (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 73, N'Greatest Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 77, N'Misplaced Childhood', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 88, N'Nevermind', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 89, N'Compositores', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 93, N'Bark at the Moon (Remastered)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 93, N'Blizzard of Ozz', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 93, N'Diary of a Madman (Remastered)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 93, N'No More Tears (Remastered)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 93, N'Speak of the Devil', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 94, N'Walking Into Clarksdale', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 95, N'The Beast Live', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 96, N'Live On Two Legs [Live]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 96, N'Riot Act', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 96, N'Ten', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 96, N'Vs.', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 97, N'Dark Side Of The Moon', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 98, N'Greatest Hits I', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 98, N'Greatest Hits II', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 98, N'News Of The World', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 99, N'New Adventures In Hi-Fi', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 100, N'Raul Seixas', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 101, N'By The Way', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 101, N'Californication', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 104, N'Retrospective I (674-1980)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 105, N'Santana - As Years Go By', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 105, N'Santana Live', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 105, N'Supernatural', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 109, N'Maquinarama', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 109, N'O Samba Poconé', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 110, N'A-Sides', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 113, N'Core', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 116, N'[1997] Black Light Syndrome', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 119, N'Beyond Good And Evil', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 120, N'The Doors', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 122, N'The Police Greatest Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 123, N'Every Kind of Light', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 124, N'Hot Rocks, 1964-1971 (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 124, N'No Security', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 124, N'Voodoo Lounge', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 125, N'My Generation - The Very Best Of The Who', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'Achtung Baby', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'B-Sides 1980-1990', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'How To Dismantle An Atomic Bomb', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'Pop', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'Rattle And Hum', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'The Best Of 1980-1990', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'War', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 128, N'Zooropa', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 130, N'Diver Down', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 130, N'The Best Of Van Halen, Vol. I', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 130, N'Van Halen III', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 130, N'Van Halen', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 132, N'Contraband', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 2, N'A Copland Celebration, Vol. I', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 15, N'Górecki: Symphony No. 3', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (4, 16, N'The Last Night of the Proms', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 17, N'Sibelius: Finlandia', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 18, N'Mozart: Symphonies Nos. 40 & 41', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 22, N'Carmina Burana', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 23, N'A Soprano Inspired', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 30, N'Scheherazade', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (1, 34, N'SCRIABIN: Vers la flamme', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 45, N'Adams, John: The Chairman Dances', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 47, N'Pachelbel: Canon & Gigue', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 49, N'Respighi:Pines of Rome', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 49, N'Strauss: Waltzes', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 58, N'Nielsen: The Six Symphonies', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 62, N'Mascagni: Cavalleria Rusticana', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 69, N'Weill: The Seven Deadly Sins', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 74, N'Tchaikovsky: The Nutcracker', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 79, N'Szymanowski: Piano Works, Vol. 1', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 81, N'Berlioz: Symphonie Fantastique', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 81, N'Prokofiev: Romeo & Juliet', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 86, N'Mozart: Chamber Music', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 87, N'The Best of Beethoven', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 91, N'Bach: The Brandenburg Concertos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 102, N'Purcell: The Fairy Queen', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 103, N'Haydn: Symphonies 99 - 104', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 106, N'Handel: The Messiah (Highlights)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 107, N'Prokofiev: Symphony No.1', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 108, N'Wagner: Favourite Overtures', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 117, N'South American Getaway', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 121, N'English Renaissance', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 127, N'Bach: Toccata & Fugue in D Minor', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 134, N'Bach: Goldberg Variations', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 135, N'Bartok: Violin & Viola Concertos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (2, 136, N'Bach: The Cello Suites', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 3, N'Worlds', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 8, N'Quiet Songs', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 13, N'Warner 25 Anos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 19, N'The Best Of Billy Cobham', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 40, N'Outbreak', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 55, N'Quanta Gente Veio ver--Bônus De Carnaval', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 60, N'Blue Moods', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 82, N'Miles Ahead', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 82, N'The Essential Miles Davis [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 82, N'The Essential Miles Davis [Disc 2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 111, N'Heart of the Night', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (3, 111, N'Morning Dance', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (4, 11, N'Frank', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (4, 131, N'Axé Bahia 2001', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (5, 12, N'Ring My Bell', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (5, 29, N'Le Freak', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (5, 42, N'MacArthur Park Suite', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 13, N'Chill: Brazil (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 25, N'Prenda Minha', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 25, N'Sozinho Remix Ao Vivo', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 28, N'Cássia Eller - Sem Limite [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 31, N'Minha Historia', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 32, N'Afrociberdelia', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 32, N'Da Lama Ao Caos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 36, N'Na Pista', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 41, N'Djavan Ao Vivo - Vol. 02', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 41, N'Djavan Ao Vivo - Vol. 1', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 44, N'The Best of Ed Motta', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 46, N'Elis Regina-Minha História', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 48, N'Unplugged', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 51, N'Deixa Entrar', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 54, N'Roda De Funk', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 55, N'Quanta Gente Veio Ver (Live)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 57, N'Meus Momentos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 66, N'Jorge Ben Jor 25 Anos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 67, N'Jota Quest-1995', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 72, N'Mais Do Mesmo', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 75, N'Duos II', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 76, N'Chill: Brazil (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 78, N'Barulhinho Bom', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 83, N'Milton Nascimento Ao Vivo', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 83, N'Minas', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 90, N'Olodum', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 92, N'Acústico MTV', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 92, N'Arquivo II', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 92, N'Arquivo Os Paralamas Do Sucesso', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 126, N'Serie Sem Limite (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 126, N'Serie Sem Limite (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 131, N'Sambas De Enredo 2001', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 131, N'Vozes do MPB', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 133, N'Vinicius De Moraes', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (6, 137, N'Ao Vivo [IMPORT]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 14, N'Plays Metallica By Four Cellos', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 20, N'Alcohol Fueled Brewtality Live! [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 20, N'Alcohol Fueled Brewtality Live! [Disc 2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 21, N'Black Sabbath Vol. 4 (Remaster)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 21, N'Black Sabbath', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 24, N'Chemical Wedding', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 56, N'Faceless', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 59, N'Use Your Illusion II', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'A Real Dead One', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'A Real Live One', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Live After Death', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'No Prayer For The Dying', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Piece Of Mind', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Powerslave', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Rock In Rio [CD1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Rock In Rio [CD2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Seventh Son of a Seventh Son', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'Somewhere in Time', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 61, N'The Number of The Beast', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 68, N'Living After Midnight', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 73, N'Greatest Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'...And Justice For All', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Black Album', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Garage Inc. (Disc 1)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Garage Inc. (Disc 2)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Load', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Master Of Puppets', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'ReLoad', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'Ride The Lightning', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 80, N'St. Anger', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 84, N'Motley Crue Greatest Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 85, N'Ace Of Spades', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 93, N'Tribute', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (7, 114, N'Mezmerize', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (8, 15, N'Revelations', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (8, 26, N'Cake: B-Sides and Rarities', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (8, 27, N'Carried to Dust (Bonus Track Version)', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (8, 33, N'Carry On', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (8, 115, N'Temple of the Dog', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (9, 35, N'Acústico MTV [Live]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (9, 35, N'Cidade Negra - Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (9, 73, N'Greatest Hits', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (9, 129, N'UB40 The Best Of - Volume Two [UK]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 48, N'The Cream Of Clapton', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 48, N'Unplugged', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 61, N'Iron Maiden', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 112, N'In Step', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 118, N'Live [Disc 1]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
                INSERT INTO [dbo].[Albums] ([GenreId], [ArtistId], [Title], [Price], [AlbumArtUrl]) VALUES (10, 118, N'Live [Disc 2]', CAST(8.99 AS Decimal(18, 2)), N'/Content/Images/placeholder.gif')
            ");
        }
        
        public override void Down()
        {
        }
    }
}
